language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm

before_install:
  - sudo npm install -g bower

install:
  - npm install
  - bower install
  - composer install --dev

before_script:
  - gulp deploy
  - cp .env.example .env

script:
  - ./bin/robo test
