language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm

install:
  - npm install -g bower
  - composer install --dev
  - bower install

before_script:
  - cp .env.example .env
  - ./bin/robo clean
  - ./bin/robo assets

script:
  - ./bin/robo test

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

notifications:
  slack: restless:HoHWQbIAj4M1g2fm9o2Ba3PR
