language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm

install:
  - npm install -g bower
  - composer install --dev
  - bower install

before_script:
  - ./bin/robo clean
  - ./bin/robo assets
  - cp .env.example .env

script:
  - ./bin/robo test

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm


